### ISSUE TITLE
No longer working in Classic

### ISSUE THREAD

**Issue by vaindil** [NielsHeltner/wowhead-quick-link#10]
The addon is no longer working in Classic. I don't get any errors, ctrl+C just opens my character info instead of the normal panel with the link. This happens with all addons except for this one disabled, so it's not a conflict with something else.

Thanks for the addon in general, it saves me so much time!

**Comment by NielsHeltner** [comment]
It sounds like the keybind might have gotten unbound. If you go to Key Bindings -> AddOns, is "Generate Wowhead Link" bound to anything?

**Comment by vaindil** [comment]
I just checked, it is bound, but the addon is magically working today. I didn't change anything, I have no idea why it didn't work yesterday. Sorry to waste your time, and thanks again for the awesome addon!

**Comment by NielsHeltner** [comment]
No worries. There currently is an issue where the keybind will get unbound on UI reloads (but fixes itself after a relog) - that might have been what caused it.
