### ISSUE TITLE
Doesn't work for some pets in the new auction house

### ISSUE THREAD

**Issue by cremor** [NielsHeltner/wowhead-quick-link#11]
(I'm not sure if you monitor the issues created on CurseForge, so I'll create it here on GitHub too. Link to CurseForge issue: https://www.curseforge.com/wow/addons/wowhead-quick-link/issues/5)

I found a weird issue in the new auction house. If you search for pets, the addon only works (shows the dialog) for some pets. It seems like it only works for pets that I already own.

It also behaves a bit different depending on the current auction house page:

* On the result list it simply works (shows the dialog) or doesn't (nothing happens).
* In the detail view of a single pet it behaves the same as on the result list page if you hover over a single item listing in the bottom list or if you hover over the big icon above the list.
But if you hover over the big name of the pet above the list, it actually opens a dialog. But if I don't own the pet already the link in that dialog is only for the generic "pet cage" item, not for the specific pet.

**Comment by NielsHeltner** [comment]
Well this is kind of embarrassing -- I haven't been receiving notifications for issues on CurseForge, so they've been completely ignored.

Thank you for the bug report - this has now been fixed as of commit d149ae85fcaca93e9355938a1acae4c7ff3b7452.
