### ISSUE TITLE
Support for the transmog collection window

### ISSUE THREAD

**Issue by cremor** [NielsHeltner/wowhead-quick-link#12]
Is it possible to add support for the transmog collection window?
If yes, please also consider those item styles that have multiple sources. A link should be generated for the currently active source (which can be changed by pressing Tab).

**Comment by NielsHeltner** [comment]
Support for both tabs (Items and Sets) of the transmog/appearance window, which also take the currently selected style into account, has been added as of 40e37193df61a9081ae4c3354ac35698ac782e81.

Two notes:
1. Illusions are not supported, as Wowhead does not have pages for illusion themselves (e.g. the illusion "Blood Draining" has illusion ID 5392, but Wowhead only has the spell that applies the illusion to a weapon (https://www.wowhead.com/spell=174979/illusion-blood-draining). It doesn't seem like there is an ingame way to link the two.
2. While the items of transmog sets are supported, the sets themselves are not. This boils down to one of two issues, depending on the set: either Wowhead doesn't have the set in its database (i.e. pretty much any raid set after tier 18); or the setID found ingame does not much Wowhead's setID.
