### ISSUE TITLE
TBC Support

### ISSUE THREAD

**Issue by nezorflame** [NielsHeltner/wowhead-quick-link#16]
Hi!
The addon needs some love for the TBC Classic release.
While you can manually set the prefix to "tbc.", the actual link is always wrong, stuck on one item from your inventory instead of picking what you're pointing at.
Original issue: https://www.curseforge.com/wow/addons/wowhead-quick-link/issues/6

**Comment by vaindil** [comment]
I'm hoping to spend some time on this in the next few days and submit a PR when I get it figured out. Not an addon expert, but I've done a few PRs here, I can probably figure it out.

**Comment by nezorflame** [comment]
Great! Let me know if you need to test it in the future.
