### ISSUE TITLE
New packaging setup

### ISSUE THREAD

**Issue by vaindil** [NielsHeltner/wowhead-quick-link#18]
Hey @NielsHeltner, hope all is well. I'd like to set up the repository to use [BigWigsMods/packager](https://github.com/BigWigsMods/packager) if you're okay with that, as the CurseForge system doesn't seem to be working (plus it doesn't properly handle having separate versions for each game version). This packager seems to be the accepted way of doing this now, otherwise we would have to upload packages manually every time.

I do not have admin permissions on the repository, so I can't tweak the necessary settings. Would you be able to handle this? The repository should be ready to go, I can trigger the first build once this is done (or you can by tagging the latest commit as `2.13.0` whenever you're ready).

Only a couple of things need to be done:

1. Disable the existing webhook that tells CurseForge to run its auto-packager.
2. Add a repository-level secret called `CF_API_KEY` with the CurseForge API key needed to upload files. I'm happy to use my own key, I just don't have access to add secrets (I guess it requires admin permissions on the repo). You should be able to add it from [this page](https://github.com/NielsHeltner/wowhead-quick-link/settings/secrets/actions) (or through the repo settings > "Secrets").

Let me know if I can help, and thank you!

**Comment by NielsHeltner** [comment]
Sounds great, thanks for looking into this :)
I've removed the existing CurseForge webhook and added the `CF_API_KEY` secret with the same API key value as the webhook used before

**Comment by vaindil** [comment]
Perfect, thank you! I tagged 2.13.0 and pushed it, and the GitHub action ran perfectly. [Logs are here](https://github.com/NielsHeltner/wowhead-quick-link/actions), and it automatically created the release [here](https://github.com/NielsHeltner/wowhead-quick-link/releases/tag/2.13.0) too. CurseForge uploads worked properly as well, and my local client updated them correctly.

Thanks again!
