### ISSUE TITLE
Hotkeys stopped working

### ISSUE THREAD

**Issue by derrickb** [NielsHeltner/wowhead-quick-link#20]
Just installed the addon version 2.13.2-bcc on TBC 2.5.2
It worked great the first time I used it. CTRL+C brought up the addon popup with links.

After closing and relaunching the game, the hotkey no longer does anything. Using CTRL+C just brings up the character screen. CTRL+SHIFT+C similarly does not bring up any addon popup.
Typing /wql does bring up the options, so the addon must be loaded, just no longer responding to the hotkey.

I tried disabling all other addons except this one, but the issue persisted.

**Comment by derrickb** [comment]
Update: I saw [this comment here](https://github.com/NielsHeltner/wowhead-quick-link/issues/10#issuecomment-549119576) and checked my key bindings. The binding had been cleared. I set it to CTRL+C and it's working again.

**Comment by vaindil** [comment]
Since this was resolved, I'll close this out. I apologize for the extremely delayed reply, please feel free to open another issue if you encounter other bugs in the future!
