### ISSUE TITLE
Error when hovering over buffs

### ISSUE THREAD

**Issue by Vettic** [NielsHeltner/wowhead-quick-link#29]
51x ...dOns/WowheadQuickLink/WowheadQuickLinkStrategies.lua:459: attempt to call global 'UnitAura' (a nil value)
[string "@WowheadQuickLink/WowheadQuickLinkStrategies.lua"]:459: in function <...dOns/WowheadQuickLink/WowheadQuickLinkStrategies.lua:458>
[string "=[C]"]: in function `SetUnitAura'
[string "@Blizzard_BuffFrame/Mainline/BuffFrame.lua"]:662: in function <...aceBlizzard_BuffFrame/Mainline/BuffFrame.lua:645>

Locals:
tooltip = GameTooltip {
 ItemTooltip = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 supportsDataRefresh = true
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 waitingForData = false
 shoppingTooltips = <table> {
 }
 updateTooltipTimer = 0.033000
 TextRight1 = GameTooltipTextRight1 {
 }
 supportsItemComparison = true
 textRight1Font = "GameTooltipHeaderText"
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
unit = "player"
index = 1
filter = "HELPFUL"
(*temporary) = <table> {
}
(*temporary) = 10
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 1
(*temporary) = "HELPFUL"
(*temporary) = "attempt to call global 'UnitAura' (a nil value)"
tooltipStates = <table> {
  = <table> {
 }
  = <table> {
 }
}

**Comment by vaindil** [comment]
I just pushed [2.15.20](https://github.com/NielsHeltner/wowhead-quick-link/releases/tag/2.15.20) to fix this, it should be live on CurseForge shortly. Thank you!
