### ISSUE TITLE
support for "Classic Quest Log"

### ISSUE THREAD

**Issue by rml9ty** [NielsHeltner/wowhead-quick-link#31]
I would love to be able to also get the id from quests shown in the Classic Quest log. that would be amazing <3

https://legacy.curseforge.com/wow/addons/classic-quest-log

**Comment by vaindil** [comment]
Just published [2.16.1](https://github.com/NielsHeltner/wowhead-quick-link/releases/tag/2.16.1), which adds support for Classic Quest Log. It should be live on CurseForge in the next 10 minutes or so. Thanks!
