### ISSUE TITLE
Not working in Classic/SoD (I found solution)

### ISSUE THREAD

**Issue by GsynthChris** [NielsHeltner/wowhead-quick-link#33]
The API for GetMouseFocus() in Classic Era was changed to be the same as in Retail. 

GetMouseFocus() becomes GetMouseFoci()[1]

In the file WowheadQuickLink.lua

Line 39
Changed GetMouseFocus() to GetMouseFoci()[1]

**Comment by vaindil** [comment]
2.16.4 will be live shortly to fix this. I don't currently have an active subscription, so let me know if anything else is broken as I couldn't test it myself. Thank you!
