### ISSUE TITLE
Not working with toy box

### ISSUE THREAD

**Issue by cremor** [NielsHeltner/wowhead-quick-link#7]
The addon does not work with toys in the toy box collection window. Instead of the toy I get an item link from some item in my bags.

**Comment by NielsHeltner** [comment]
This seems to be a bug with the Blizzard UI.

On a fresh relog, hovering over a toy in the toybox will give the correct link (through GameTooltip:GetItem()). However if you hover over any item beforehand, and then attempt to get the link for the toy, GameTooltip:GetItem() will return the last item you've hovered over.

**Comment by cremor** [comment]
Interesting. You might want to report that here: https://github.com/Stanzilla/WoWUIBugs/issues

(Unrelated: While browsing that issue list I found Stanzilla/WoWUIBugs#12 which talks about a workaround for the keybind reload issue.)

**Comment by NielsHeltner** [comment]
I will definitely do that, and thank you for that find! I'll look into implementing the workaround.

**Comment by cremor** [comment]
Seems like this was fixed by Blizzard.
